
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_backend_using_lanchain
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server_using_lanchain:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:
    image: postgres:15
    container_name: chatwithdoc_postgres_using_lanchain
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_using_lanchain_data:/var/lib/postgresql/data


  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant_using_lanchain
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_using_lanchain_data:/qdrant/storage    

volumes:
  postgres_using_lanchain_data:
  qdrant_using_lanchain_data: