# Generated by Django 5.2.15 on 2026-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='storage_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
