# Generated by Django 4.2.16 on 2026-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'WORD'), ('html', 'HTML'), ('url', 'URL')], max_length=10)),
                ('source_name', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
