# Generated by Django 4.2.16 on 2026-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_logic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_active',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='UPLOADING', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(max_length=20),
        ),
    ]
